# Generated by Django 3.0.2 on 2020-01-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT TITLE', max_length=60)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('coord_x', models.IntegerField(default=999)),
                ('coord_y', models.IntegerField(default=999)),
                ('n_to_x', models.IntegerField(default=0)),
                ('n_to_y', models.IntegerField(default=0)),
                ('e_to_x', models.IntegerField(default=0)),
                ('e_to_y', models.IntegerField(default=0)),
                ('s_to_x', models.IntegerField(default=0)),
                ('s_to_y', models.IntegerField(default=0)),
                ('w_to_x', models.IntegerField(default=0)),
                ('w_to_y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentRoom', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
