# Generated by Django 3.0.2 on 2020-01-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='e_to_x',
            new_name='e_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='e_to_y',
            new_name='n_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to_x',
            new_name='s_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='n_to_y',
            new_name='w_to',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='coord_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='coord_y',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to_x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to_y',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to_x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to_y',
        ),
    ]
