# Generated by Django 3.0.2 on 2020-01-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlie', '0002_auto_20200108_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
